# fly.toml app configuration file generated for axol-backend on 2025-06-09T22:24:39-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'axol-backend'
primary_region = 'gdl'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'
  DJANGO_SETTINGS_MODULE = "myproject.settings.production"


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
