# Generated by Django 4.2.9 on 2024-11-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0002_remove_politicacabana_cabana_alter_cabana_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabana',
            name='slug',
        ),
        migrations.AlterField(
            model_name='cabana',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cabanas', to='cabanas.ubicacion'),
        ),
    ]
