# Generated by Django 4.2.9 on 2024-11-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0003_remove_cabana_slug_alter_cabana_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabana',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
