# Generated by Django 4.2.9 on 2024-11-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0005_alter_cabana_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabana',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
