# Generated by Django 4.2.9 on 2024-11-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0006_alter_cabana_slug'),
    ]

    operations = [
    ]
