# Generated by Django 4.2.9 on 2024-11-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendador',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
