# Generated by Django 5.1.2 on 2025-07-02 05:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('icono', models.CharField(blank=True, help_text='Ruta del icono en el frontend', max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cabana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('capacidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('costo_por_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('inactiva', 'Inactiva')], default='disponible', max_length=20)),
                ('superficie', models.FloatField(blank=True, help_text='Superficie en m²', null=True)),
                ('numero_habitaciones', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_banos', models.PositiveIntegerField(blank=True, null=True)),
                ('permite_mascotas', models.BooleanField(default=False)),
                ('reglas_casa', models.TextField(blank=True, null=True)),
                ('hora_checkin', models.TimeField(blank=True, null=True)),
                ('hora_checkout', models.TimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabanas', to='teams.team')),
                ('servicios', models.ManyToManyField(blank=True, to='cabanas.servicio')),
            ],
            options={
                'verbose_name': 'Cabaña',
                'verbose_name_plural': 'Cabañas',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='ImagenCabana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='cabanas/%Y/%m/')),
                ('es_principal', models.BooleanField(default=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='cabanas.cabana')),
            ],
            options={
                'verbose_name': 'Imagen de Cabaña',
                'verbose_name_plural': 'Imágenes de Cabañas',
                'ordering': ['orden', '-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='cabanas.cabana')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('cabana', 'usuario')},
            },
        ),
        migrations.AddIndex(
            model_name='cabana',
            index=models.Index(fields=['estado'], name='cabanas_cab_estado_f759f0_idx'),
        ),
        migrations.AddIndex(
            model_name='cabana',
            index=models.Index(fields=['slug'], name='cabanas_cab_slug_ee6524_idx'),
        ),
    ]
