# Generated by Django 5.1.2 on 2025-06-17 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrendador',
            fields=[
                ('id_arrendador', models.AutoField(primary_key=True, serialize=False)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrendador', to='usuarios.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='usuarios.persona')),
            ],
        ),
    ]
