# Generated by Django 4.2.9 on 2024-11-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabanas', '__first__'),
        ('usuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.arrendador')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('noches', models.IntegerField(blank=True, null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.arrendador')),
            ],
        ),
        migrations.CreateModel(
            name='PaqueteCabana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabanas.cabana')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.paquete')),
            ],
            options={
                'unique_together': {('paquete', 'cabana')},
            },
        ),
        migrations.CreateModel(
            name='PaqueteActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.paquete')),
            ],
            options={
                'unique_together': {('paquete', 'actividad')},
            },
        ),
    ]
